

# Site Settings
title: 						"Taurus Omejia"
email: 						"taurus@tauruso.com"
description: 				"I am on a Journey learning Web Development. I'm having a blast and I want you along for the ride."
baseurl: 					""
url: 						"/"
logourl: 					"/assets/img/taurus/Taurus.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Taurus Omejia"
author_url: 				"http://tauruso.com"
author_bio: 				"Software Engineer: I like the web so I build things for it! Tools I use include: C# ASP.NET MVC WebApi - Python | Django - Angular - Typescript - Sql"
author_email: 				"taurus@tauruso.com"
author_image: 				"/assets/img/taurus/Taurus.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/tauruso"
facebook_url: 				"http://facebook.com/suruato"
github_url:  				"http://github.com/bolenton"
youtube_url:
dribbble_url:
googleplus_url:
instagram_url:
pinterest_url:
linkedin_url:  				"http://linkedin.com/taurusomejia"


# Theme Settings
theme_disqus_shortname: 	"tauruso"
theme_google_comments: 		false
theme_analytics_id: 		"UA-61908404-1"
theme_analytics_domain: 	"tauruso.com"
theme_reading_time: 		true
theme_autoload_comments: 	true
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

